name: SAMT
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.8.0
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=41.0.2
  - cuda=11.8.0
  - cuda-cccl=12.2.53
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=11.8.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=11.8.86
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.8.86
  - cuda-demo-suite=11.8.86
  - cuda-documentation=11.8.86
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-memcheck=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.8.89
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.8.86
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.8.86
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-nvvp=11.8.87
  - cuda-profiler-api=12.2.53
  - cuda-runtime=11.8.0
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-visual-tools=11.8.0
  - cudatoolkit=11.8.0
  - cudnn=8.9.2.26
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - git=2.40.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.3.53
  - libcurand-dev=10.3.3.53
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpmath=1.2.1
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nsight-compute=2022.3.0.22
  - numpy=1.25.0
  - numpy-base=1.25.0
  - nvidia-ml=7.352.0
  - openssl=3.0.9
  - pillow=9.4.0
  - pip=23.2.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.12
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - requests=2.31.0
  - setuptools=68.0.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - addict
      - blinker
      - click
      - colorama
      - contourpy
      - cycler
      - fairscale
      - fire
      - flask
      - flask-cors
      - fonttools
      - fsspec
      - huggingface-hub
      - imageio
      - importlib-metadata
      - itsdangerous
      - kiwisolver
      - lazy-loader
      - matplotlib
      - opencv-python
      - platformdirs
      - pycocotools
      - pywavelets
      - regex
      - safetensors
      - scikit-image
      - scipy
      - sentencepiece
      - six
      - spatial-correlation-sampler
      - supervision
      - termcolor
      - tifffile
      - timm
      - tokenizers
      - torchaudio
      - torchvision
      - tqdm
      - transformers
      - werkzeug
      - xmltodict
      - yapf
      - zipp
